replicaCount: 3

image:
  repository: nhostert/myapp
  pullPolicy: Always
  tag: ""

imagePullSecrets: []
nameOverride: "ycit021-myapp"
fullnameOverride: "ycit021-myapp"

serviceAccount:
  create: true
  annotations: {}
  name: "ycit021-svc"

podAnnotations: {}

podSecurityContext: {}


securityContext: {}

service:
  type: LoadBalancer
  port: 80
  targetport: 80

ingress:
  enabled: false
  # Below values to be used in a next iteration of the app
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: myapp
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 
  targetCPUUtilizationPercentage: 80


nodeSelector: {}

tolerations: []

selectorLabels:
  app: myapp

# Making sure we don't have 2 pods running on the same node
affinity: 
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: "app.kubernetes.io/instance"
          operator: In
          values:
          - myapp
      topologyKey: kubernetes.io/hostname